<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="MockObj" Id="{459c9319-db86-4d6a-b774-a97d62f0aee0}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK MockObj EXTENDS CyclicBase IMPLEMENTS I_Initialise
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="Cycle" Id="{2fdaa782-1cce-42d3-b0fd-0a553501ea73}">
      <Declaration><![CDATA[{warning 'Add method implementation '}
METHOD Cycle : Base_Library.HRESULT
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="Initialise" Id="{b6fb438d-078a-4d9d-ba13-f31f733124cc}">
      <Declaration><![CDATA[{warning 'Add method implementation '}
METHOD Initialise : Base_Library.HRESULT
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
  </POU>
</TcPlcObject>